[
    # specify directory to the delta table
    import-delta: 'file:///',

    # specify cipher query
    cipher: 'MERGE (u:User {uid: row.uid})
                ON CREATE SET
                u.firstName = row.firstName,
                u.lastName = row.lastName,
                u.age = toInteger(row.age),
                u.cityLived = row.cityLived;',

    cipher: 'y'
]